poszukiwania/api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

app_name = 'rest_framework'
#
# router = routers.SimpleRouter()
# router.register(r'', views.api_overview)

urlpatterns = [
    # path('users/', views.UserList.as_view(), name='user_list'),
    # path('users/<int:id>', views.UserDetail.as_view(), name='user_detail'),
    path('', views.api_overview, name='overwiew'),
    path('list/', views.FindList.as_view(), name='finds_list'),
    path('list/<int:pk>', views.FindDetail.as_view(), name='finds_detail'),
]

poszukiwania/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import path, reverse_lazy
from django.utils.translation import gettext_lazy as _

from . import views


app_name = 'poszukiwania'

urlpatterns = [
    path(_('add/'), views.create, name='create'),
    path(_('login/'), auth_views.LoginView.as_view(), name='login'),
    path(_('logout/'), auth_views.LogoutView.as_view(), name='logout'),
    path(_('password_change/'), auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('poszukiwania:password_change_done')), name='password_change'),
    path(_('password_change/done/'), auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path(_('password_reset/'), auth_views.PasswordResetView.as_view(success_url=reverse_lazy('poszukiwania:password_reset_done')), name='password_reset'),
    path(_('password_reset/done/'), auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(_('reset/<uidb64>/<token>/'), auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('poszukiwania:password_reset_complete')), name='password_reset_confirm'),
    path(_('reset/done/'), auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path(_('register/'), views.register, name='register'),
    path('search/', views.search, name='search'),
    path('style/<str:style>/', views.style, name='style'),
    path('', views.objects_list, name='objects_list'),
    path(_('delete/<int:id>/'), views.delete_objects, name='delete'),
    path(_('update/<int:id>/'), views.update, name='update'),
    path('<slug:category_slug>/', views.objects_list, name='objects_list_by_category'),
    path('<int:year>/<int:month>/<int:day>/<slug:object_slug>/<int:id>/', views.object_detail, name='object_detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL)

znajdki/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('api/'), include('poszukiwania.api.urls', namespace='rest_framework')),
    path(_('rosetta/'), include('rosetta.urls')),
    path('', include('poszukiwania.urls', namespace='poszukiwania')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL)

poszukiwania/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Map(models.Model):
    point = models.JSONField(null=True)
    description = models.CharField(blank=True, max_length=250, default='Znajdka')

    class Meta:
        app_label = 'poszukiwania'

    def description_f(self):
        return '{}'.format(self.description)


class Category(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('poszukiwania:objects_list_by_category', args=[self.slug])


class Rzeczy(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default='test')
    location = models.OneToOneField(Map, on_delete=models.CASCADE, primary_key=True)
    category = models.ForeignKey(Category, related_name='rzeczy', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique_for_date='publish', blank=True)
    year = models.PositiveIntegerField(blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    image_obverse = models.ImageField('image_obverse', upload_to='rzeczy/%Y/%m/%d', default='empty.png')
    image_reverse = models.ImageField('image_revers', upload_to='rzeczy/%Y/%m/%d', default='empty.png')
    comments = models.TextField(blank=True, null=True)
    catalog_number = models.PositiveSmallIntegerField(default=0)
    update = models.DateField(auto_now=True)
    publish = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['publish']

    def get_absolute_url(self):
        return reverse('poszukiwania:object_detail', args=[self.publish.year,
                                                           self.publish.month,
                                                           self.publish.day,
                                                           self.slug,
                                                           self.pk])

poszukiwania/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core import validators
from django.utils.translation import gettext_lazy as _

from .models import Rzeczy, Map


class RzeczyForm(forms.ModelForm):
    class Meta:
        model = Rzeczy
        fields = ('category', 'name', 'slug', 'year', 'text', 'image_obverse', 'image_reverse', 'comments',
                  'catalog_number')
        widgets = {
            'category': forms.Select(attrs={'class': "form-control"}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('name')}),
            'slug': forms.HiddenInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': _('description')}),
            'year': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': _('year')}),
            'image_obverse': forms.FileInput(attrs={'class': 'form-control'}),
            'image_reverse': forms.FileInput(attrs={'class': 'form-control'}),
            'comments': forms.Textarea(attrs={'class': 'form-control', 'placeholder': _('comments'), 'rows': '6'}),
            'catalog_number': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': _('catalog_number')}),
        }


class MapForm(forms.ModelForm):
    class Meta:
        model = Map
        fields = ('point',)
        widgets = {'point': forms.TextInput(attrs={'class': 'json_form'})}


class EmailForm(validators.EmailValidator):
    message = _('Enter a valid email address.')


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {'username': forms.TextInput(attrs={'class': 'register_input'}),
                   'email': forms.TextInput(attrs={'class': 'register_input'}),
                   'password1': forms.TextInput(attrs={'class': 'register_input'}),
                   'password2': forms.TextInput(attrs={'class': 'register_input'})}

    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
    }

poszukiwania/api/views.py
from ..models import Rzeczy, Category
from .serializers import FindsSerializer, CategorySerializer, UserSerializer
from django.shortcuts import redirect
from rest_framework.decorators import api_view
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView


class FindList(APIView):
    def get(self, request):
        finds = Rzeczy.objects.all()
        serializer = FindsSerializer(finds, many=True)
        return Response(serializer.data)


class FindDetail(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'znajdki_detail.html'

    def get(self, request, pk):
        find = Rzeczy.objects.get(pk=pk)
        serializer = FindsSerializer(find)
        return Response(serializer.data)

    def put(self, request, pk):

        find = Rzeczy.objects.get(pk=pk)
        serializer = FindsSerializer(find, data=request.data)
        if not serializer.is_valid():
            return Response({'serializer': serializer})
        serializer.save()
        return redirect('rest-framework:finds_detail', pk=pk)


@api_view(['GET'])
def api_overview(request):
    api_urls = {
        'List': 'list/',
        'Detail': 'list/<int:pk>/',
    }
    return Response(api_urls)

poszukiwania/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import redirect
from django.utils.text import slugify

from .forms import SignUpForm, RzeczyForm, MapForm
from .models import Category, Rzeczy


def style(request, style):
    list_styles = ['table', 'thumbnail']
    if style in list_styles:
        request.session['style'] = style
        return redirect('poszukiwania:objects_list')


@login_required()
def objects_list(request, category_slug=None, session=1):

    if session:
        request.session.setdefault('style', 'thumbnail')

    kat = False
    monety = False

    categories = Category.objects.all()
    objects = Rzeczy.objects.filter(user=request.user)
    recently = Rzeczy.objects.order_by('-publish')[:5]

    sort = request.GET.get('sort')

    maps = [r.location for r in objects]
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        objects = Rzeczy.objects.filter(category=category, user=request.user)
        maps = [r.location for r in objects]
        kat = True

    if sort:
        objects = objects.order_by(sort)
        if sort == 'catalog_number':
            objects = Rzeczy.objects.filter(catalog_number__gt=0).order_by(sort)

    page = request.GET.get('page')
    paginator = Paginator(objects, 20)

    try:
        objects_pagination = paginator.page(page)
    except PageNotAnInteger:
        objects_pagination = paginator.page(1)
    except EmptyPage:
        objects_pagination = paginator.page(paginator.num_pages)
    return render(request, 'main/lista.html', {'objects': objects_pagination,
                                               'categories': categories,
                                               'monety': monety,
                                               'kat': kat,
                                               'page': page,
                                               'recently': recently,
                                               'maps': maps
                                               })


@login_required
def object_detail(request, *args, **kwargs):
    object = Rzeczy.objects.get(pk=kwargs['id'])
    point = object.location
    form = RzeczyForm(instance=object)
    return render(request, 'main/detail.html', {'form': form,
                                                'point': point,
                                                'object': object,
                                                })


def register(request):
    if request.method == 'POST':
        user_form = SignUpForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect('poszukiwania:login')
    else:
        user_form = SignUpForm()
    return render(request, 'main/register.html', {'user_form': user_form, })


@login_required
def create(request):
    work = None
    type_side = 'create'
    create_form = RzeczyForm(request.POST or None, request.FILES or None)
    map_form = MapForm(request.POST or None)
    if create_form.is_valid() and map_form.is_valid():
        opis = create_form.cleaned_data['name']
        new_map = map_form.save(commit=False)
        new_map.description = opis
        new_map.save()
        new_item = create_form.save(commit=False)
        new_item.location = new_map
        new_item.slug = slugify(new_item.name)
        new_item.user = request.user
        new_item.save()
        work = 1
    return render(request, 'main/create.html', {'form': create_form,
                                                'map': map_form,
                                                'type': type_side,
                                                'work': work
                                                })


def search(request):
    if request.is_ajax():
        znajdka = request.POST.get('znajdka')
        objects = Rzeczy.objects.filter(name__icontains=znajdka)
        if len(objects) > 0 and len(znajdka) > 0:
            data = []
            for object in objects:
                item = {
                    'pk': object.pk,
                    'name': object.name,
                    'image_obverse': str(object.image_obverse.url),
                    'image_reverse': str(object.image_reverse.url),
                    'publish': object.publish,
                    'url': object.get_absolute_url()
                }
                data.append(item)
            list = data
        else:
            list = 'no objects'
        return JsonResponse({'data': list})
    return JsonResponse({})


def update(request, *args, **kwargs):
    object = Rzeczy.objects.get(pk=kwargs['id'])
    type_side = 'update'
    point = object.location
    form = RzeczyForm(request.POST or None, request.FILES or None, instance=object)
    map_form = MapForm(request.POST or None, instance=object.location)
    if form.is_valid() and map_form.is_valid():
        data = form.cleaned_data
        update_map = map_form.save(commit=False)
        update_map.description = data['name']
        update_map.save()
        main = form.save(commit=False)
        main.location = update_map
        main.slug = slugify(data['name'])
        main.user = request.user
        main.save()
        return redirect('poszukiwania:objects_list')
    return render(request, 'main/create.html', {'form': form,
                                                'map': map_form,
                                                'point': point,
                                                'type': type_side
                                                })


def delete_objects(request, **kwargs):
    Rzeczy.objects.get(pk=kwargs['id']).delete()
    return redirect('poszukiwania:objects_list')

poszukiwania/templates/main/create.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% load i18n %}
{% load static %}

{% block title %}
    {% trans 'Dodawanie rzeczy' %}
 {% endblock %}

{% block content %}
    {{  mapa_form.media }}

    <div class='container' style="background-color: whitesmoke; width: 60%; height: auto; margin: auto">
            <form action='.' method='post' enctype='multipart/form-data'>
                {% csrf_token %}

                <div class="row" style="height: auto;">
                    <div class="col-1"></div>
                    <div class="col-3" >
                        <div class="form_create" style="margin-top: 0">
                            <label>{% trans "Category" %}</label>
                            {{ form.category }}
                        </div>
                        <div class="form_create">
                            {{ form.name }}
                        </div>
                        <div class="form_create">
                            {{ form.year }}
                        </div>
                        <div class="form_create">
                            {{ form.text }}
                        </div>
                        <div class="form_create">
                            <label>{% trans "image_obverse" %}</label>
                            {{ form.image_obverse }}
                        </div>
                        <div class="form_create">
                            <label>{% trans "image_reverse" %}</label>
                            {{ form.image_reverse }}
                        </div>
                        <div class="form_create">
                            {{ form.catalog_number }}
                        </div>
                        <div class="form_create">
                        </div>
                    </div>
                    <div class="col-1"></div>
                    <div class="col-6"  style="margin-top: 1.5rem;">
                        <div class="map" id="map" style="height: 28rem;">
                            {{ map.point }}

                        </div>
                              {% if map.errors %}
                                <p><h4 style="color: firebrick">{% trans 'Mark the point on the map' %}</h4></p>
                            {% endif %}
                        <div class="form_create" style="height: 14rem;">
                            {{ form.comments }}
                        </div>
                            <div style="width: auto; float: right; height: 2rem;">
                                {% if type == 'create' %}
                                    <button class="btn btn-secondary" id="button_create" type="submit" value="create">{% trans "create" %}</button>
                                {% else %}
                                    <button class="btn btn-secondary" id="button_update" type="submit" value="create">{% trans "update" %}</button>
                                {% endif %}
                                <a class='btn btn-secondary' href="{% url 'poszukiwania:objects_list' %}">{% trans "back" %}</a>
                            </div>

                    </div>

                </div>


            </form>

        </div>
 <style type="text/css">
        #id_geolocation_map{
            width: 100%;
        }
    </style>
    <script type="text/javascript" src="{% static 'js/test.js' %}"></script>
{% endblock %}

poszukiwania/templates/main/detail.html
 {% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}
    {% trans 'Detail' %}
{% endblock %}

{% block content %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 250px;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}
th{
    width: 9rem;
}
tr:nth-child(even) {
  background-color: #dddddd;
}
#id_text{
    height: 18rem;
    width: 20rem;
}
.button_detail{
    height: 2.5rem;
}
</style>
    <div class="detail">
        <div class="panel">
            <div style="height: auto;width: auto; float: right">
                <a class="btn btn-secondary button_detail" href="{% url 'poszukiwania:objects_list' %}">{% trans "back" %}</a>
                <a class="btn btn-secondary button_detail" href="{% url 'poszukiwania:update' object.pk %}">{% trans "update" %}</a>
                <a class="btn btn-dark button_detail" href="{% url 'poszukiwania:delete' object.pk %}" onclick="return confirm('Are you sure')">{% trans "delete" %}<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
</svg></a>
            </div>
        </div>
        <div>
            <div class="text_center">
                <img class="image_detail"  src="{{ object.image_obverse.url }}">
                <img class="image_detail"  src="{{ object.image_reverse.url }}">
            </div>
        </div>
        <div style="  width: 40rem; margin: auto; margin-top: 2rem; margin-bottom: 2rem;">
            <div style="width: 20rem; height: 20rem; float: left">
                <div style="float: left";>
                    <table style="width: 20rem" id="table_detail">
                        <tr>
                            <th>{% trans "Name" %}</th>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <th>{% trans "User" %}</th>
                            <td>{{ object.user }}</td>
                        </tr>
                        <tr>
                            <th>{% trans "Category" %}</th>
                            <td>{{ object.category }}</td>
                        </tr>
                        <tr>
                            <th>{% trans "Year" %}</th>
                            <td>{{ object.year }}</td>
                        </tr>
                        <tr>
                            <th>{% trans "Catalog_number" %}</th>
                            <td>{{ object.catalog_number }}</td>
                        </tr>
                            <th>{% trans "Update" %}</th>
                            <td>{{ object.update }}</td>
                        </tr>
                        </tr>
                            <th>{% trans "Publish" %}</th>
                            <td>{{ object.publish }}</td>
                        </tr>
                    </table>
                </div>

            </div>
            <div style="width: 15rem; height: 20rem; float: left">
                {{ form.text }}
            </div>
        </div>

        <div id='mapid'  class="mapid" style="margin: auto; margin-top: 50px; width: 600px">
        <script type="text/javascript">
        console.log()
            var satellite = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}');
            var street = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png?{foo}', {foo: 'bar'});
               var m = L.map('mapid',   {center: [{{ point.point.lat|safe }}, {{ point.point.lng|safe }}],
                                        zoom: 15,
                                        layers: [satellite]});
            var baseMaps = {
                "Grayscale": satellite,
                "Streets": street}
            L.control.groupedLayers(baseMaps).addTo(m);
            L.marker({{ point.point|safe }}).addTo(m);
        </script>
        </div>
        <div style="width: 40rem; margin: auto; margin-top: 2rem; ">
            {{ form.comments }}
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/detail.js' %}"></script>
 {% endblock %}

poszukiwania/templates/main/lista.html
 {% extends "base.html" %}

{% load custom_template_tags %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="container-fluid" >
        <div class="row panel">
            {% if request.user.is_authenticated %}
                <div class="col-2">
                    <div class="panel_link">
                        <div id='toggle' class="btn-toggle-nav" onclick="sidebar()"></div>
                        <div class='addSign'>
                            <a  id='add_object_link' href="{% url 'poszukiwania:create' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="2rem" height="2rem" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                                <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-3 ms-auto" style>
                    <div>
                        <form id="form_search">
                            {% csrf_token %}
                            <input placeholder="search" id="input_search">
                        </form>
                    </div>
                </div>
                <div class="col-3 ms-3">
                    <span class="cracked float_right">ZNAJDKI</span>
                </div>
            {% else %}
                <div class="text_center">
                    <p><h3>Welcome to Detectorist Catalog.</h3></p>
                    <h3><a href="{% url 'poszukiwania:login' %}" >{% trans "Login" %}</a>|<a href="{% url 'poszukiwania:register' %}">{% trans "Register" %}</a></h3>
                </div>
            {% endif %}
        </div>
            {% if request.user.is_authenticated %}


                <div  class="row lista" style="background-color: ghostwhite">
                    {% include 'main/list/function.html' %}
                    <div class="col-9">
                        <div class="list_search_objects not-visible"></div>
                        {%  include 'main/list/array_of_objects.html' %}

                        {% include 'main/list/pagination.html' %}
                        <div id="mapid" class="mapid">
                        <script src="https://rawgithub.com/ismyrnow/Leaflet.groupedlayercontrol/master/src/leaflet.groupedlayercontrol.js"></script>
                            <script type="text/javascript">


                                var satellite = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/' +
                                        'World_Imagery/MapServer/tile/{z}/{y}/{x}');
                                var street = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png?{foo}', {foo: 'bar'});
                                   var m = L.map('mapid',   {center: [52.012, 21.922],
                                                            zoom: 15,
                                                            layers: [satellite]});
                                var baseMaps = {
                                    "Grayscale": satellite,
                                    "Streets": street}

                                L.control.groupedLayers(baseMaps).addTo(m);


                                {#L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/' +#}
                                {#        'World_Imagery/MapServer/tile/{z}/{y}/{x}').addTo(m)#}
                                    {% for e in maps %}

                                        L.marker({{ e.point|safe }}).addTo(m).bindPopup('{{ e.description_f }}');
                                    {% endfor %}
                            </script>
                        </div>

                    </div>
                </div>
            {% endif %}
    </div>
 <script type="text/javascript" src="{% static 'js/list.js' %}"></script>
{% endblock %}

poszukiwania/templates/main/register.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="login">
    <div style="height: 1rem;"></div>
    <h3 style="text-align: center">{% trans "Register Account" %}</h3>
    {% if user_form.errors %}
        {{ user_form.errors }}
    {% endif %}

    <form action='.' method='post'>
         {% csrf_token %}
        <div class="center_register">
            <div>
                <div class="line" >
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-file-person-fill" viewBox="0 0 16 16">
                    <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm-1 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm-3 4c2.623 0 4.146.826 5 1.755V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-1.245C3.854 11.825 5.377 11 8 11z"/></svg> </div>
                <div class="line">{{ user_form.username }}</div>
            </div>
        </div>
         <div class="center_register">
            <div>
                <div class="line" >
                     <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                        <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
                     </svg></div>
                <div class="line">{{ user_form.email }}</div>
            </div>
        </div>
        <div class="center_register">
            <div>
                <div class="line"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-key-fill" viewBox="0 0 16 16">
                      <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                    </svg></div>
                <div class="line">{{ user_form.password1 }}</div>
            </div>
        </div>
        <div class="center_register">
            <div>
                <div class="line"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-key-fill" viewBox="0 0 16 16">
                      <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                    </svg></div>
                <div class="line">{{ user_form.password2 }}</div>
            </div>
        </div>
         <div class="center_register"style=" margin-bottom: 20px;">
            <p><button type="submit" class="btn btn-light">{% trans "Register" %}</button></p>
         </div>
        <div class="center_register" style="margin-bottom: 20px;">
            <p style="font-size: 20px;">{% trans "Already have an account?" %} <a style="font-size: 20px; color: green;" href="{% url 'poszukiwania:login' %}">{% trans "Login" %}</a></p>
         </div>
    </form>
</div>
{% endblock %}