poszukiwania/api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

app_name = 'rest_framework'
#
# router = routers.SimpleRouter()
# router.register(r'', views.api_overview)

urlpatterns = [
    # path('users/', views.UserList.as_view(), name='user_list'),
    # path('users/<int:id>', views.UserDetail.as_view(), name='user_detail'),
    path('', views.api_overview, name='overwiew'),
    path('list/', views.FindList.as_view(), name='finds_list'),
    path('list/<int:pk>', views.FindDetail.as_view(), name='finds_detail'),
]

poszukiwania/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import path, reverse_lazy
from django.utils.translation import gettext_lazy as _

from . import views


app_name = 'poszukiwania'

urlpatterns = [
    path(_('add/'), views.create, name='create'),
    path(_('login/'), auth_views.LoginView.as_view(), name='login'),
    path(_('logout/'), auth_views.LogoutView.as_view(), name='logout'),
    path(_('password_change/'), auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('poszukiwania:password_change_done')), name='password_change'),
    path(_('password_change/done/'), auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path(_('password_reset/'), auth_views.PasswordResetView.as_view(success_url=reverse_lazy('poszukiwania:password_reset_done')), name='password_reset'),
    path(_('password_reset/done/'), auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(_('reset/<uidb64>/<token>/'), auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('poszukiwania:password_reset_complete')), name='password_reset_confirm'),
    path(_('reset/done/'), auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path(_('register/'), views.register, name='register'),
    path('search/', views.search, name='search'),
    path('style/<str:style>/', views.style, name='style'),
    path('', views.objects_list, name='objects_list'),
    path(_('delete/<int:id>/'), views.delete_objects, name='delete'),
    path(_('update/<int:id>/'), views.update, name='update'),
    path('<slug:category_slug>/', views.objects_list, name='objects_list_by_category'),
    path('<int:year>/<int:month>/<int:day>/<slug:object_slug>/<int:id>/', views.object_detail, name='object_detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL)

znajdki/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('api/'), include('poszukiwania.api.urls', namespace='rest_framework')),
    path(_('rosetta/'), include('rosetta.urls')),
    path('', include('poszukiwania.urls', namespace='poszukiwania')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL)

poszukiwania/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Map(models.Model):
    point = models.JSONField(null=True)
    description = models.CharField(blank=True, max_length=250, default='Znajdka')

    class Meta:
        app_label = 'poszukiwania'

    def description_f(self):
        return '{}'.format(self.description)


class Category(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('poszukiwania:objects_list_by_category', args=[self.slug])


class Rzeczy(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default='test')
    location = models.OneToOneField(Map, on_delete=models.CASCADE, primary_key=True)
    category = models.ForeignKey(Category, related_name='rzeczy', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique_for_date='publish', blank=True)
    year = models.PositiveIntegerField(blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    image_obverse = models.ImageField('image_obverse', upload_to='rzeczy/%Y/%m/%d', default='empty.png')
    image_reverse = models.ImageField('image_revers', upload_to='rzeczy/%Y/%m/%d', default='empty.png')
    comments = models.TextField(blank=True, null=True)
    catalog_number = models.PositiveSmallIntegerField(default=0)
    update = models.DateField(auto_now=True)
    publish = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['publish']

    def get_absolute_url(self):
        return reverse('poszukiwania:object_detail', args=[self.publish.year,
                                                           self.publish.month,
                                                           self.publish.day,
                                                           self.slug,
                                                           self.pk])

poszukiwania/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core import validators
from django.utils.translation import gettext_lazy as _

from .models import Rzeczy, Map


class RzeczyForm(forms.ModelForm):
    class Meta:
        model = Rzeczy
        fields = ('category', 'name', 'slug', 'year', 'text', 'image_obverse', 'image_reverse', 'comments',
                  'catalog_number')
        widgets = {
            'category': forms.Select(attrs={'class': "form-control"}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('name')}),
            'slug': forms.HiddenInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': _('description')}),
            'year': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': _('year')}),
            'image_obverse': forms.FileInput(attrs={'class': 'form-control'}),
            'image_reverse': forms.FileInput(attrs={'class': 'form-control'}),
            'comments': forms.Textarea(attrs={'class': 'form-control', 'placeholder': _('comments'), 'rows': '6'}),
            'catalog_number': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': _('catalog_number')}),
        }


class MapForm(forms.ModelForm):
    class Meta:
        model = Map
        fields = ('point',)
        widgets = {'point': forms.TextInput(attrs={'class': 'json_form'})}


class EmailForm(validators.EmailValidator):
    message = _('Enter a valid email address.')


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {'username': forms.TextInput(attrs={'class': 'register_input'}),
                   'email': forms.TextInput(attrs={'class': 'register_input'}),
                   'password1': forms.TextInput(attrs={'class': 'register_input'}),
                   'password2': forms.TextInput(attrs={'class': 'register_input'})}

    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
    }

poszukiwania/api/views.py
from ..models import Rzeczy, Category
from .serializers import FindsSerializer, CategorySerializer, UserSerializer
from django.shortcuts import redirect
from rest_framework.decorators import api_view
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView


class FindList(APIView):
    def get(self, request):
        finds = Rzeczy.objects.all()
        serializer = FindsSerializer(finds, many=True)
        return Response(serializer.data)


class FindDetail(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'znajdki_detail.html'

    def get(self, request, pk):
        find = Rzeczy.objects.get(pk=pk)
        serializer = FindsSerializer(find)
        return Response(serializer.data)

    def put(self, request, pk):

        find = Rzeczy.objects.get(pk=pk)
        serializer = FindsSerializer(find, data=request.data)
        if not serializer.is_valid():
            return Response({'serializer': serializer})
        serializer.save()
        return redirect('rest-framework:finds_detail', pk=pk)


@api_view(['GET'])
def api_overview(request):
    api_urls = {
        'List': 'list/',
        'Detail': 'list/<int:pk>/',
    }
    return Response(api_urls)

poszukiwania/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import redirect
from django.utils.text import slugify

from .forms import SignUpForm, RzeczyForm, MapForm
from .models import Category, Rzeczy


def style(request, style):
    list_styles = ['table', 'thumbnail']
    if style in list_styles:
        request.session['style'] = style
        return redirect('poszukiwania:objects_list')


@login_required()
def objects_list(request, category_slug=None, session=1):

    if session:
        request.session.setdefault('style', 'thumbnail')

    kat = False
    monety = False

    categories = Category.objects.all()
    objects = Rzeczy.objects.filter(user=request.user)
    recently = Rzeczy.objects.order_by('-publish')[:5]

    sort = request.GET.get('sort')

    maps = [r.location for r in objects]
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        objects = Rzeczy.objects.filter(category=category, user=request.user)
        maps = [r.location for r in objects]
        kat = True

    if sort:
        objects = objects.order_by(sort)
        if sort == 'catalog_number':
            objects = Rzeczy.objects.filter(catalog_number__gt=0).order_by(sort)

    page = request.GET.get('page')
    paginator = Paginator(objects, 20)

    try:
        objects_pagination = paginator.page(page)
    except PageNotAnInteger:
        objects_pagination = paginator.page(1)
    except EmptyPage:
        objects_pagination = paginator.page(paginator.num_pages)
    return render(request, 'main/lista.html', {'objects': objects_pagination,
                                               'categories': categories,
                                               'monety': monety,
                                               'kat': kat,
                                               'page': page,
                                               'recently': recently,
                                               'maps': maps
                                               })


@login_required
def object_detail(request, *args, **kwargs):
    object = Rzeczy.objects.get(pk=kwargs['id'])
    point = object.location
    form = RzeczyForm(instance=object)
    return render(request, 'main/detail.html', {'form': form,
                                                'point': point,
                                                'object': object,
                                                })


def register(request):
    if request.method == 'POST':
        user_form = SignUpForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect('poszukiwania:login')
    else:
        user_form = SignUpForm()
    return render(request, 'main/register.html', {'user_form': user_form, })


@login_required
def create(request):
    work = None
    type_side = 'create'
    create_form = RzeczyForm(request.POST or None, request.FILES or None)
    map_form = MapForm(request.POST or None)
    if create_form.is_valid() and map_form.is_valid():
        opis = create_form.cleaned_data['name']
        new_map = map_form.save(commit=False)
        new_map.description = opis
        new_map.save()
        new_item = create_form.save(commit=False)
        new_item.location = new_map
        new_item.slug = slugify(new_item.name)
        new_item.user = request.user
        new_item.save()
        work = 1
    return render(request, 'main/create.html', {'form': create_form,
                                                'map': map_form,
                                                'type': type_side,
                                                'work': work
                                                })


def search(request):
    if request.is_ajax():
        znajdka = request.POST.get('znajdka')
        objects = Rzeczy.objects.filter(name__icontains=znajdka)
        if len(objects) > 0 and len(znajdka) > 0:
            data = []
            for object in objects:
                item = {
                    'pk': object.pk,
                    'name': object.name,
                    'image_obverse': str(object.image_obverse.url),
                    'image_reverse': str(object.image_reverse.url),
                    'publish': object.publish,
                    'url': object.get_absolute_url()
                }
                data.append(item)
            list = data
        else:
            list = 'no objects'
        return JsonResponse({'data': list})
    return JsonResponse({})


def update(request, *args, **kwargs):
    object = Rzeczy.objects.get(pk=kwargs['id'])
    type_side = 'update'
    point = object.location
    form = RzeczyForm(request.POST or None, request.FILES or None, instance=object)
    map_form = MapForm(request.POST or None, instance=object.location)
    if form.is_valid() and map_form.is_valid():
        data = form.cleaned_data
        update_map = map_form.save(commit=False)
        update_map.description = data['name']
        update_map.save()
        main = form.save(commit=False)
        main.location = update_map
        main.slug = slugify(data['name'])
        main.user = request.user
        main.save()
        return redirect('poszukiwania:objects_list')
    return render(request, 'main/create.html', {'form': form,
                                                'map': map_form,
                                                'point': point,
                                                'type': type_side
                                                })


def delete_objects(request, **kwargs):
    Rzeczy.objects.get(pk=kwargs['id']).delete()
    return redirect('poszukiwania:objects_list')

poszukiwania/templates/main/list/array_of_objects.html
<div class="objects">
    {% if request.session.style == 'thumbnail' %}
        {% for object in objects %}
            <div  {% if forloop.counter|divisibleby:2 %} class="ciemny obj"{% else %} class="jasny obj"{% endif %}>
            <a href="{{ object.get_absolute_url }}">
                <table>
                   <tr>
                       <td>
                           <div style="display: flex">
                               <img class="image" src="{{ object.image_obverse.url }}">
                               <img class="image" src="{{ object.image_reverse.url }}">
                           </div>
                       </td>
                   </tr>
                    <tr>
                        <td>
                            <div class="float_left text-justify"><h4>{{ object.name }}</h4></div>
                            <div class="float_right">
                                <div>
                                    <h6 style="color: darkslategrey">
                                        {% if object.year != None %}
                                            {{ object.year }}
                                        {% endif %}
                                    </h6>
                                </div>
                                {% if object.catalog_number != 0 %}
                                    <div><h6 style="color: darkred">{{ object.catalog_number}}</h6></div>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                </table>
             </a>
        </div>
    {% endfor %}
    {% elif request.session.style == 'table' %}
        <table class="width" id="table_table" >
            <tbody>
                <tr>
                    <th class="tdth">Name</th>
                    <th class="tdth">Category</th>
                    <th class="tdth">Year</th>
                    <th class="tdth">Catalog Number</th>
                    <th class="tdth">Publish</th>
                    <hr>
                </tr>
                {% for object in objects %}
                        <tr class="tr_table">
                            <td class="tdth">
                                <a href="{{ object.get_absolute_url }}">
                                    {{ object.name }}
                                </a>
                            </td>
                            <td class="tdth">{{ object.category }}</td>
                            <td class="tdth">
                                {% if object.year != None %}
                                        {{ object.year }}
                                {% endif %}
                            </td>
                            <td class="tdth">
                                {% if object.catalog_number != 0 %}
                                        {{ object.catalog_number}}
                                {% endif %}
                            </td>
                            <td class="tdth">{{ object.publish }}</td>
                        </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
</div>

poszukiwania/templates/main/list/function.html
{% load i18n %}
<div id="colFunction" class="col-3">
    <div id='sidebar' class="sidebar">
        <div class="toggleFunctions">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
             <select  class="btn  width " onchange="location = this.value">
                <option class="btn">{% trans "Language" %}</option>
                {% for language in languages %}
                    <option  value="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                            {{ language.name_local }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="toggleFunctions">
            <a class="btn toggleFunctions width" href="#">{% trans 'Help' %}</a>
        </div>
        <div class="toggleFunctions">
            <a class="btn toggleFunctions width" href="{% url 'poszukiwania:password_change' %}">{% trans 'Change password' %}</a>
        </div>
        <hr>
        <div class="space_function"></div>
        <div>
            <a class="btn toggleFunctions" id="logout"  href="{% url 'poszukiwania:logout' %}"><h5>{% trans "Logout" %}</h5></a>
        </div>

    </div>
    <div>
        <table style="width: 100%; margin-top: 0.5rem;">
            <tbody>
                {% comment %} <tr>
                    <td>
                        <a class="btn row_table function_button"  id='add_object_link' href="{% url 'poszukiwania:create' %} " >{% trans 'Add an object' %}</a>
                    </td>
                </tr> {% endcomment %}
                <tr>
                    <td>
                        <p></p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <select class="btn  row_table function_button" id="category_selected" onchange="location = this.value;">
                            <option>{% trans "Categories" %}</option>
                            <option value="{% url 'poszukiwania:objects_list' %}" >{% trans "All" %}</option>
                            {% for category in categories %}
                                <option  id='{{ category.slug }}' value="{{ category.get_absolute_url }}"{% if category == current_category %}selected="selected"{% endif %} >{{ category.title }}</option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                         <select class="btn  row_table function_button" onchange="location = this.value">
                            <option value=""><strong>{% trans "Sort by" %}</strong></option>
                            <option value="?sort={{ 'name' }}">{% trans "Name" %}</option>
                            <option value="?sort={{ 'year' }}">{% trans "Year" %}</option>
                            <option value="?sort={{ 'publish' }}">{% trans "Publication" %}</option>
                            <option value="?sort={{ 'catalog_number' }}">{% trans "Catalog_numbers" %}</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                         <select class="btn row_table function_button" id="select_style" onchange="location = this.value">
                            <option><strong>{% trans "Style" %}</strong></option>
                            <option value="{% url 'poszukiwania:style' 'thumbnail' %}">{% trans "Thumbnail" %}</option>
                            <option value="{% url 'poszukiwania:style' 'table' %}">{% trans "Table" %}</option>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div id="latest_objects">
        <h3 class="text_center">{% trans "Recently added" %}</h3>
            <ul>
                {% for object in recently %}
                <li><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></li>
                {% endfor %}
            </ul>
    </div>

</div>

poszukiwania/templates/main/list/pagination.html
<div style="width: 100%">
<div class="col-md-3 offset-md-5 paginator">
  <ul class="pagination">
        {% if objects.has_previous %}
            <li class="page-item">
                <a class="page-link"  href="?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link"  href="#">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        {% if objects.has_previous %}
            <li class="page-item">
                <a class="page-link"  href="?page={{ objects.previous_page_number }}">
                    <span aria-hidden="true">&lt;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link"  href="#">
                    <span aria-hidden="true">&lt;</span>
                </a>
            </li>
        {% endif %}
        {% for number_page in objects.paginator.page_range %}
            {% if number_page == objects.number %}
                <li class="page-item active"><a class="page-link" href="#">{{ number_page }}</a></li>
            {% else %}
                {% if number_page > objects.number|add:'-3' and  number_page < objects.number|add:'3' %}
                     <li class="page-item"><a class="page-link" href="?page={{ number_page }}">{{ number_page }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if objects.has_next %}
             <li class="page-item">
                <a class="page-link" href="?page={{ objects.next_page_number }}">
                    <span aria-hidden="true">&gt;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">
                    <span aria-hidden="true">&gt;</span>
                </a>
            </li>
        {% endif %}
        {% if objects.has_next %}
            <li class="page-item ">
                <a class="page-link" href="?page={{ objects.paginator.num_pages }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
  </ul>
</div>
</div>